export const UPDATE_IMAGES="UPDATE_IMAGES";
export const UPDATE_COMPRESSED_IMAGES="UPDATE_COMPRESSED_IMAGES";
export const UPDATE_IMAGE_URLS="UPDATE_IMAGE_URLS";
export const UPDATE_SELECTED_IMAGE="UPDATE_SELECTED_IMAGE";
